config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'home' => "static_pages#home"
  get 'help' => "static_pages#help"
  get 'about' => "static_pages#about"
  get 'contact' => "static_pages#contact"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get  'signup' => 'users#new'
  get  'login' => 'sessions#new'
  post  'login' => 'sessions#create'
  delete  'logout' => 'sessions#destroy'
  post 'follow/:id' => 'relationships#follow', as: 'follow' 
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' 
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :tweets, only: [:create, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end

app/models/user.rb
class User < ApplicationRecord
    has_many :tweets, dependent: :destroy
    has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
    has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
    has_many :following_user, through: :follower, source: :followed
    has_many :follower_user, through: :followed, source: :follower
    #データを保存する前にメアドを小文字にする。
    before_save { email.downcase! } 
    # name は必ず存在し、長さが50字以内であること
    validates :name, presence: true, length: { maximum: 50 }
    # メールアドレスのフォーマットを「正規表現」を使って指定
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    # email は必ず存在し、長さが５０字以内
    # メールアドレスのフォーマットになっている
    # メールアドレスはユニーク（同じデータが存在してはいけない）
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

    # ユーザーをフォローする
    def follow(user_id)
        follower.create(followed_id: user_id)
    end
    # ユーザーのフォローを外す
    def unfollow(user_id)
        follower.find_by(followed_id: user_id).destroy
    end
    # フォロー確認をおこなう
    def following?(user)
        following_user.include?(user)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper

    private
        def logged_in_user
            unless logged_in?
                flash[:danger] = "ログインしてください"
                redirect_to login_url
            end
        end
end

app/controllers/foo_controller.rb
class FooController < ActionController::Base
    def hello
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    def follow
        current_user.follow(params[:id])
        redirect_to user_path
    end
    def unfollow
        current_user.unfollow(params[:id])
        redirect_to user_path
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      # ToDo: エラーメッセージを作成する
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @tweet = current_user.tweets.build
      @tweets = Tweet.all.order(created_at: "DESC").paginate(page: params[:page], per_page: 10) if logged_in?
    end
  end

  def help
  end

  def about
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_action :logged_in_user, only: [:create, :destroy, :edit, :update]
    before_action :correct_user,   only: [:destroy, :edit, :update]

    def create
        @tweet = current_user.tweets.build(tweet_params)
        if @tweet.save
            flash[:success] = "投稿されました！"
            redirect_to root_url
        else
            render 'static_pages/home'
        end
    end

    def edit
        @tweet = Tweet.find(params[:id])
    end

    def update
        @tweet = Tweet.find(params[:id])
        if @tweet.update(tweet_params)
            flash[:success] = "変更を保存しました。"
            redirect_to root_url
        else
            render 'edit'
        end
    end
    
    def destroy
        @tweet.destroy
        flash[:success] = "削除しました"
        redirect_to request.referrer || root_url
    end

    private

        def tweet_params
            params.require(:tweet).permit(:content)
        end

        def correct_user
            @tweet = current_user.tweets.find_by(id: params[:id])
            if @tweet.nil?
                flash[:danger] = "不正なアクセスです"
                redirect_to root_url
            end
        end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :following, :followers]
  before_action :correct_user,   only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @tweets = @user.tweets
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params) 
    if @user.save
      log_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def following
    @title = "フォロー中"
    @user  = User.find(params[:id])
    @users = @user.following_user.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "フォロワー"
    @user  = User.find(params[:id])
    @users = @user.follower_user.paginate(page: params[:page])
    render 'show_follow'
  end

  private
	
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    # 正しいユーザーかどうか確認
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end

  # 渡されたユーザーがログイン済みユーザーであればtrueを返す
  def current_user?(user)
    user == current_user
  end
  
  def current_user
    if session[:user_id]
        if @current_user.nil?
            @current_user = User.find_by(id: session[:user_id])
        else
            @current_user
        end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foo/hello.erb
<h1>Hello World!</h1>

<p>presented by K.Aihara</p>
<p>with A さん</p>
<p>with B さん</p>

<p>さらにAさん</p>
<p>さらにBさん</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "sample app", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   root_path %></li>
            <li><%= link_to "Help",   help_path %></li>
            <% if logged_in? %>
            <%# ログインされている時 %>
              <li><%= link_to "Users", '#' %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Log out", logout_path, method: :delete %>
                  </li>
                </ul>
              </li>
            <% else %>
              <%# ログインされていない時 %>
              <li><%= link_to "Log in", login_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <footer class="footer">
        <nav>
          <ul>
            <li><%= link_to "About",   about_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
          </ul>
        </nav>
      </footer>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>About</h1>

app/views/static_pages/contact.html.erb
<h1>contact</h1>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <h1><%= current_user.name %></h1>
        <p><%= link_to "プロフィールを見る", current_user %></p>
        <p><%= current_user.tweets.count %> ツイート </p>
      </section>
      <section class="tweet_form">
        <%= form_for(@tweet) do |f| %>
          <% if @tweet.errors.any? %>
            <div id="error_explanation">
              <div class="alert alert-danger">
                <%= @tweet.errors.count %>つのエラーがあります。
              </div>
              <ul>
                <% @tweet.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="field">
            <%= f.text_area :content, placeholder: "こんにちは" %>
          </div>
          <%= f.submit "投稿", class: "btn btn-primary" %>
        <% end %>
      </section>
    </aside>

    <div class="col-md-8">
    <% if @tweets.any? %>
        <%= will_paginate @tweets %>
        <ol class="tweets">
            <% @tweets.each do |tweet| %>
                <li id="tweet-<%= tweet.id %>">
                    <span class="user"><%= link_to tweet.user.name, tweet.user %></span>
                    <span class="content"><%= tweet.content %></span>
                    <span class="timestamp">
                        投稿日 <%= time_ago_in_words(tweet.created_at) %> 前
                        <% if current_user?(tweet.user) %>
                          <%= link_to "編集", edit_tweet_path(tweet)%>
                          <%= link_to "削除", tweet, method: :delete, data: { confirm: "削除しますか？" } %>
                        <% end %>
                    </span>
                </li>
            <% end %>
        </ol>
        <%= will_paginate @tweets %>
    <% end %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>ようこそ！</h1>

    <h2>
      まずはサインアップしてみよう！
    </h2>

    <%= link_to "サインアップ！", signup_path, class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>ツイート編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@tweet) do |f| %>
      <% if @tweet.errors.any? %>
        <div id="error_explanation">
            <div class="alert alert-danger">
                <%= @tweet.errors.count %>つのエラーがあります。
            </div>
            <ul>
                <% @tweet.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
      <% end %>

      <%= f.label :content %>
      <%= f.text_field :content, class: 'form-control' %>

      <%= f.submit "変更を保存する", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1>プロフィール更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <% if @user.errors.any? %>
        <div id="error_explanation">
            <div class="alert alert-danger">
            The form contains <%= pluralize(@user.errors.count, "error") %>.
            </div>
            <ul>
            <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
            </ul>
        </div>
      <% end %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "変更を保存する", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
        <% if @user.errors.any? %>
        <div id="error_explanation">
            <div class="alert alert-danger">
            The form contains <%= pluralize(@user.errors.count, "error") %>.
            </div>
            <ul>
            <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
            </ul>
        </div>
        <% end %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
    <aside class="col-md-4">
        <section class="user_info">
            <h1>
            <%= @user.name %>
            </h1>
            <p>
                <% if current_user != @user %>
                    <% if current_user.following?(@user) %>
                        <%= link_to 'フォロー解除', unfollow_path(@user.id), method: :POST %>
                    <% else %>
                        <%= link_to 'フォローする', follow_path(@user.id), method: :POST %>
                    <% end %>
                <% end %>
            </p>
        </section>
        <section>
        <div class="stats">
            <a href="<%= following_user_path(@user) %>">
                <strong id="follower" class="stat">
                <%= @user.follower.count %>
                </strong>
                フォロー
            </a>
            <a href="<%= followers_user_path(@user) %>">
                <strong id="followed" class="stat">
                <%= @user.followed.count %>
                </strong>
                フォロワー
            </a>
        </div>
        </section>
    </aside>
    <div class="col-md-8">
    <% if @user.tweets.any? %>
        <h3>ツイート (<%= @user.tweets.count %>)</h3>
        <ol class="tweets">
            <% @tweets.each do |tweet| %>
                <li id="tweet-<%= tweet.id %>">
                    <span class="user"><%= link_to tweet.user.name, tweet.user %></span>
                    <span class="content"><%= tweet.content %></span>
                    <span class="timestamp">
                        投稿日 <%= time_ago_in_words(tweet.created_at) %> 前
                    </span>
                </li>
            <% end %>
        </ol>
    <% end %>
    </div>
</div>

app/views/users/show_follow.html.erb
<div class="row">
    <aside class="col-md-4">
        <section class="user_info">
            <h1><%= @user.name %></h1>
            <p><%= link_to "プロフィールを見る", @user %></p>
            <p><b>ツイート:</b> <%= @user.tweets.count %></p>
        </section>
        <section class="stats">
            <div class="stats">
                <a href="<%= following_user_path(@user) %>">
                    <strong id="follower" class="stat">
                    <%= @user.follower.count %>
                    </strong>
                    フォロー
                </a>
                <a href="<%= followers_user_path(@user) %>">
                    <strong id="followed" class="stat">
                    <%= @user.followed.count %>
                    </strong>
                    フォロワー
                </a>
            </div>
            <% if @users.any? %>
            <div class="user_avatars">
                <% @users.each do |user| %>
                <% end %>
            </div>
            <% end %>
        </section>
    </aside>
    <div class="col-md-8">
        <h3><%= @title %></h3>
        <% if @users.any? %>
            <ul class="users follow">
                <% @users.each do |user| %>
                    <li id="tweet-<%= user.id %>">
                        <span class="user"><%=  user.name %></span>
                    </li>
                <% end %>
            </ul>
            <%= will_paginate %>
        <% end %>
    </div>
</div>